inherit_from: .rubocop_todo.yml

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'db/schema.rb'
    - 'spec/requests/*'
    - 'spec/models/*'
    - 'config/routes.rb'
    - 'controllers/api/v1/jobs_controller.rb'

Metrics/AbcSize:
  Max: 40
  Exclude:
    - 'db/migrate/*'
  
Metrics/MethodLength:
  Enabled: false
