inherit_from: .rubocop_todo.yml

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'db/schema.rb'
    - 'spec/requests/*'
    - 'spec/models/*'
    - 'spec/factories/*'
    - 'config/routes.rb'
    - 'controllers/api/v1/jobs_controller.rb'
    - 'config/deploy.rb'

Metrics/AbcSize:
  Max: 50
  Exclude:
    - 'db/migrate/*'

Metrics/MethodLength:
  Enabled: false

Lint/HandleExceptions:
  Exclude:
    - 'config/unicorn/production.rb'

Style/AsciiComments:
  Exclude:
    - 'config/deploy.rb'
    - 'config/unicorn/production.rb'

Style/GlobalVars:
  Exclude:
    - 'config/unicorn/production.rb'

Metrics/CyclomaticComplexity:
  Max: 8
  Exclude:
    - 'app/models/job.rb'

Metrics/PerceivedComplexity:
  Max: 9
  Exclude:
  - 'app/models/job.rb'


Metrics/ClassLength:
  Max: 90
  Exclude:
    - 'app/controllers/api/v1/assigns_controller.rb'
    - 'app/controllers/api/v1/jobs_controller.rb'
    - 'app/controllers/api/v1/schedules_controller.rb'