inherit_from: .rubocop_todo.yml

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'db/schema.rb'
    - 'spec/requests/*'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'
  
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
